"""Write analysis results back into the drawing as a loadable LISP file.

Drawing 600 centrelines through 600 MCP round trips is not viable, and
seeing the result on top of the drawing is the only honest way to check
geometry work. So emit one file and load it with a single call:

    system.execute_lisp  (load "<path>")

The file is written, not executed here — nothing touches the drawing until
that load runs.
"""

from __future__ import annotations

import os

# AutoCAD colour indices, one per wall thickness in rank order.
_PALETTE = [1, 3, 5, 4, 6, 2, 30, 40, 50, 60]

# Real drawings throw a tail of one-off gaps — a 3.2 cm pair here, a 1 cm
# pair there. Giving each its own layer buries the two thicknesses that
# matter under twenty that do not, so only the top ranks get their own and
# the rest share one layer that is obviously the leftovers.
_MAX_THICKNESS_LAYERS = 6


def centerlines_lisp(result: dict, out_path: str, layer: str = "MCP-WALL-CL",
                     label: bool = False) -> dict:
    """Emit the centrelines from `detect_walls` as lines, one layer per
    significant thickness so each wall type can be toggled independently.

    The generated file stays ASCII, and so does the default layer name. How
    AutoCAD decodes a .lsp it loads depends on the machine's locale, and a
    name that comes back as mojibake leaves junk layers in a real drawing.
    Pass `layer` explicitly if you want CJK and have checked it round-trips.
    """
    lines = result.get("centerlines") or []
    if not lines:
        return {"error": "no centerlines in result — run detect_walls first"}

    ranked = [p["thickness_m"] for p in result.get("thickness_peaks", [])]
    if not ranked:
        counts: dict = {}
        for p in lines:
            counts[p["thickness_m"]] = counts.get(p["thickness_m"], 0) + 1
        ranked = sorted(counts, key=lambda t: -counts[t])
    major = ranked[:_MAX_THICKNESS_LAYERS]
    other = f"{layer}-OTHER"

    body = [";; generated by autocad-mcp space.visualize - safe to erase",
            '(defun c:MCPUNDO () (command "_.-LAYER" "_D" "%s*" ""))' % layer,
            "(setvar \"CMDECHO\" 0)"]

    used = {}
    minor = 0
    for p in lines:
        t = p["thickness_m"]
        if t in major:
            name = f"{layer}-{t:g}"
            colour = _PALETTE[major.index(t) % len(_PALETTE)]
        else:
            name, colour = other, 8
            minor += 1
        if name not in used.values():
            body.append('(command "_.-LAYER" "_M" "%s" "_C" "%d" "" "")' % (name, colour))
        used[t] = name
        body.append('(command "_.-LAYER" "_S" "%s" "")' % name)
        body.append('(command "_.LINE" (list %.4f %.4f) (list %.4f %.4f) "")'
                    % (p["start"][0], p["start"][1], p["end"][0], p["end"][1]))
        if label:
            mx = (p["start"][0] + p["end"][0]) / 2
            my = (p["start"][1] + p["end"][1]) / 2
            body.append('(command "_.TEXT" (list %.4f %.4f) "" "" "%g")' % (mx, my, t))

    layers_made = sorted(set(used.values()))
    body.append("(setvar \"CMDECHO\" 1)")
    body.append('(princ "\\n%d centerlines drawn on %d layers")'
                % (len(lines), len(layers_made)))
    body.append("(princ)")

    out_path = os.path.abspath(out_path)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(body) + "\n")

    return {
        "lisp_path": out_path,
        "lines": len(lines),
        "lines_on_other_layer": minor,
        "layers_created": layers_made,
        "load_command": '(load "%s")' % out_path.replace("\\", "/"),
        "undo": "MCPUNDO deletes the generated layers and their contents.",
    }
